/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parte2;

import javax.swing.JOptionPane;

public class VectorR3 extends javax.swing.JFrame {

    /**
     * Creates new form Vector5
     */
    public VectorR3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        txtV1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtV00 = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtV01 = new javax.swing.JTextField();
        txtV02 = new javax.swing.JTextField();
        txtV11 = new javax.swing.JTextField();
        txtV12 = new javax.swing.JTextField();
        txtV10 = new javax.swing.JTextField();
        txtV20 = new javax.swing.JTextField();
        txtV21 = new javax.swing.JTextField();
        txtV22 = new javax.swing.JTextField();
        txtR00 = new javax.swing.JTextField();
        txtR01 = new javax.swing.JTextField();
        txtR02 = new javax.swing.JTextField();
        txtR12 = new javax.swing.JTextField();
        txtR11 = new javax.swing.JTextField();
        txtR10 = new javax.swing.JTextField();
        txtR20 = new javax.swing.JTextField();
        txtR21 = new javax.swing.JTextField();
        txtR22 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vectores de R3");
        setMinimumSize(new java.awt.Dimension(610, 430));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("V1:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 40, 74, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("V2:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 90, 27, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("V3:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(63, 139, 27, 20);

        txtV00.setBackground(new java.awt.Color(153, 153, 153));
        txtV00.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV00.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV00);
        txtV00.setBounds(130, 60, 50, 21);

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(490, 341, 94, 25);

        btnCalcular.setBackground(new java.awt.Color(204, 204, 204));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(470, 100, 90, 40);

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("La  Base Ortonormal de R3  es:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 200, 370, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("V1:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 241, 27, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("V2:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 273, 27, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("V3:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 301, 27, 20);

        txtV01.setBackground(new java.awt.Color(153, 153, 153));
        txtV01.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV01.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV01);
        txtV01.setBounds(230, 60, 55, 21);

        txtV02.setBackground(new java.awt.Color(153, 153, 153));
        txtV02.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV02.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV02);
        txtV02.setBounds(330, 60, 48, 21);

        txtV11.setBackground(new java.awt.Color(153, 153, 153));
        txtV11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV11.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV11);
        txtV11.setBounds(230, 110, 55, 21);

        txtV12.setBackground(new java.awt.Color(153, 153, 153));
        txtV12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV12.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV12);
        txtV12.setBounds(330, 110, 50, 21);

        txtV10.setBackground(new java.awt.Color(153, 153, 153));
        txtV10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV10);
        txtV10.setBounds(130, 110, 50, 21);

        txtV20.setBackground(new java.awt.Color(153, 153, 153));
        txtV20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV20.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV20);
        txtV20.setBounds(130, 160, 50, 21);

        txtV21.setBackground(new java.awt.Color(153, 153, 153));
        txtV21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV21.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV21);
        txtV21.setBounds(230, 160, 55, 21);

        txtV22.setBackground(new java.awt.Color(153, 153, 153));
        txtV22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtV22.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtV22);
        txtV22.setBounds(330, 160, 50, 21);

        txtR00.setEditable(false);
        txtR00.setBackground(new java.awt.Color(153, 153, 153));
        txtR00.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR00.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR00);
        txtR00.setBounds(94, 243, 150, 21);

        txtR01.setEditable(false);
        txtR01.setBackground(new java.awt.Color(153, 153, 153));
        txtR01.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR01.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR01);
        txtR01.setBounds(262, 243, 150, 21);

        txtR02.setEditable(false);
        txtR02.setBackground(new java.awt.Color(153, 153, 153));
        txtR02.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR02.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR02);
        txtR02.setBounds(420, 270, 140, 21);

        txtR12.setEditable(false);
        txtR12.setBackground(new java.awt.Color(153, 153, 153));
        txtR12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR12.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR12);
        txtR12.setBounds(420, 240, 140, 21);

        txtR11.setEditable(false);
        txtR11.setBackground(new java.awt.Color(153, 153, 153));
        txtR11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR11.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR11);
        txtR11.setBounds(262, 274, 150, 21);

        txtR10.setEditable(false);
        txtR10.setBackground(new java.awt.Color(153, 153, 153));
        txtR10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR10);
        txtR10.setBounds(94, 273, 150, 21);

        txtR20.setEditable(false);
        txtR20.setBackground(new java.awt.Color(153, 153, 153));
        txtR20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR20.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR20);
        txtR20.setBounds(94, 303, 150, 21);

        txtR21.setEditable(false);
        txtR21.setBackground(new java.awt.Color(153, 153, 153));
        txtR21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR21.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR21);
        txtR21.setBounds(262, 303, 150, 21);

        txtR22.setEditable(false);
        txtR22.setBackground(new java.awt.Color(153, 153, 153));
        txtR22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtR22.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtR22);
        txtR22.setBounds(420, 300, 140, 21);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("{");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 60, 27, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(",");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 60, 10, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("}");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 60, 27, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(",");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 60, 10, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(",");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 110, 10, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("{");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 110, 27, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(",");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(210, 110, 10, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("}");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 110, 27, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(",");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(300, 160, 10, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(",");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(210, 160, 10, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("{");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(100, 160, 27, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("}");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(380, 160, 27, 20);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra2/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea regresar?", "Confirmar",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respuesta==JOptionPane.YES_OPTION){
            new menu().setVisible(true);
            dispose();
        }
       
       
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
      
        try{
        double[][] matriz = new double[3][3];
        double[][] matrizR = new double[3][3];
        
        matriz[0][0]=Double.parseDouble(txtV00.getText());
        matriz[0][1]=Double.parseDouble(txtV01.getText());
        matriz[0][2]=Double.parseDouble(txtV02.getText());
        
        matriz[1][0]=Double.parseDouble(txtV10.getText());
        matriz[1][1]=Double.parseDouble(txtV11.getText());
        matriz[1][2]=Double.parseDouble(txtV12.getText());
        
        matriz[2][0]=Double.parseDouble(txtV20.getText());
        matriz[2][1]=Double.parseDouble(txtV21.getText());
        matriz[2][2]=Double.parseDouble(txtV22.getText());
        
       Ortonormales obj = new Ortonormales();
        
        matrizR = obj.ortonormalizacion(matriz);
        
        if(obj.determinante(matriz)==0.0){
            JOptionPane.showMessageDialog(null, "Los vectores ingresados no son una base de R3. \n Por favor inserte una base R3");
        }
        else{
            txtR00.setText(String.valueOf(matrizR[0][0]));
            txtR01.setText(String.valueOf(matrizR[0][1]));
            txtR02.setText(String.valueOf(matrizR[0][2]));
            
            txtR10.setText(String.valueOf(matrizR[1][0]));
            txtR11.setText(String.valueOf(matrizR[1][1]));
            txtR12.setText(String.valueOf(matrizR[1][2]));
            
            txtR20.setText(String.valueOf(matrizR[2][0]));
            txtR21.setText(String.valueOf(matrizR[2][1]));
            txtR22.setText(String.valueOf(matrizR[2][2]));
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, ingrese solo datos numéricos.");
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField txtR00;
    private javax.swing.JTextField txtR01;
    private javax.swing.JTextField txtR02;
    private javax.swing.JTextField txtR10;
    private javax.swing.JTextField txtR11;
    private javax.swing.JTextField txtR12;
    private javax.swing.JTextField txtR20;
    private javax.swing.JTextField txtR21;
    private javax.swing.JTextField txtR22;
    private javax.swing.JTextField txtV00;
    private javax.swing.JTextField txtV01;
    private javax.swing.JTextField txtV02;
    private javax.swing.JTextField txtV1;
    private javax.swing.JTextField txtV10;
    private javax.swing.JTextField txtV11;
    private javax.swing.JTextField txtV12;
    private javax.swing.JTextField txtV20;
    private javax.swing.JTextField txtV21;
    private javax.swing.JTextField txtV22;
    // End of variables declaration//GEN-END:variables
}
